import { AiSubNav } from "@/components/admin/AiSubNav";

export default function AdminAiLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full flex-col gap-6">
      <div>
        <h1 className="text-2xl font-black tracking-tight text-zinc-950">
          SEA-LION Engine Intelligence
        </h1>
        <p className="mt-1 text-xs text-zinc-500">
          Configure algorithmic scanning parameters and audit natural language rationales generated by the SEA-LION neural pipeline.
        </p>
      </div>

      <AiSubNav />

      <div className="w-full">{children}</div>
    </div>
  );
}
